# -*- coding: utf-8 -*-
"""
Spyde
"""
import nltk
import re
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize, sent_tokenize 
stop_words = set(stopwords.words('english'))
txt="""THEORY AMONG THE ENGLISH WHO IS DERRIDA, WHAT IS HE ? SPLENDOURS AND MISERIES OF THE ACADEMY I II III IV V CULTURAL STUDY, POETIC ART I II 
I have tried to show in this book that though the academic institutionalizing of vernacular literary study which began about a century ago had good, even inescapable reasons in its origins, its later progress has not had the effects the founders hoped for. This is largely because, once incorporated into the academy, this study had to adopt the values and principles of the academy, and develop as the institution developed. An ideal of professionalism became dominant, and teachers of English did their best to adopt it, producing an ever greater volume of critical and scholarly writing whose motive was as much career development as the expansion of knowledge. And yet, they could never become as truly professional as their colleagues in other disciplines, since â€˜literatureâ€™ did not belong in the academy and was not generated there, though criticism and scholarship might be. English, as the Newbolt Report and Leavis had insisted, was not like other academic subjects, though all the pressures of the modern academy, which include both privileges and responsibilities, have tried to make it come in line. The professionalized academic critic wanted to forget that there had been a time when criticism was part of literature; and the belief that criticism or theory could be literature in themselves was perhaps part of the process of exorcizing other values and attitudes. Poets and novelists see the situation differently, and so, indeed, do many students, who tend to want something different from what their ablest teachers wish to give them. The complex of disparate elements comprising academic English was always unstable, though they might have stayed together longer if it had not been for the demands of the academic environment.
In the 1950s, it seemed as if there might be a place for literature in the academy, so that the writing of fiction or poetry, of criticism, and the teaching of literature would become a unified form of life. As we know, it did not happen. Thirty years on, English is a large and entrenched subject, and there is no likelihood of putting the clock back, and starting again in some other way: my proposal for a division between Cultural Studies and a degree in poetry is a pragmatic proposal for a way out of current difficulties. Other factors, like the institutional need to advance knowledge, to publish, to engage in research, and generate performanceindicators, would remain, whatever new academic structures emerged.
There is, however, another way in which a useful advance might be made. Again, one looks back to the nineteenthcentury origins of English literary studies, when the first pioneers and missionaries, men such as Morley and Furnivall, travelled all over the country to talk about English literature in adult education classes and working men's clubs. Indeed, it was the pressure from this large and disadvantaged constituency that helped to establish vernacular literary education. There has always been a vigorous tradition of English studies in adult education, and indeed it was through such classes that I was myself able to become a mature student in the early 1950s. In the present situation, there is more and more scope for adult or continuing education, with an older or academically late-developing constituency. In such work there is an opportunity for English to, in a sense, escape from the academy, literally to go extra-mural, and to re-establish those connections with the larger society that were originally part of its raison d'Ãªtre . Literature classes with older people can be rewarding; they bring a longer experience of life to bear on the subject, and often a wide range of reading. They are also exempt from the demands of examination passing, assessment, and certification, that I believe have a more distorting effect in the teaching of literature than in other academic areas. The subject can be pursued for its own satisfaction. However, a difficulty with extra-mural study is that teachers have to work very hard in order to keep classes in being, since there are no external compulsions on students to attend, and their motivation and level of interest are very variable. Malcolm Bradbury's story, â€˜The Adult Education Classâ€™, nicely dramatizes the difficulties and dangers. Adult classes, in fact, require exceptionally good teaching, of a kind that may be remote from the professional ideals of many presentday academics.
At the present time, there is much interest in the English past, evoked in exhibitions commemorating historical events, and evident in the spread of museums and the great popularity of visiting country homes. This interest has several aspects. One of them, as the Left disapprovingly points out, is a mythologized version of past greatness which obfuscates the disagreeable realities of the present. Certainly there are many bogus images of the national past around, culminating in the dream world peddled abroad by the British Tourist Board (though this is, alas, what Americans and others want to visit). But people need myths of one sort or another, and the Left has its own, in memories of Wat Tyler, Cromwell, the Tolpuddle Martyrs, and the heroic industrial struggles of the past. Mythology, however partial, is better than blank amnesia. This current feeling for the past might provide a way in adult classes of shifting the emphasis from popular modern writing to earlier literature. Chaucer looked at in isolation can seem daunting, but Chaucer read in a cultural and historical context, with visual and other aids, could come alive as a great poet, speaking across six centuries, in a Gadamerian fusion of horizons. I am not, though, recommending the ideological antiquarianism of the New Historicism, which has little interest in poetry as such. This is a speculative proposal, merely, and it may fall foul of the fact that in our image-ridden culture reading is difficult, and literary texts still demand to be read , rigorously and carefully. In cultural history reading â€˜aboutâ€™ something may be good enough; in studying literature it is not.
There is a good deal more to say, and to think about, concerning the relations between the intra- and extra-mural teaching of literature. The above considerations are simply meant to signal my conviction that a change of balance is desirable, with a move away from the narrow professionalism of the academy, and a modest return to the original motives of the discipline of English. Something similar is true of literary criticism. At the moment the academy has a nearmonopoly of the subject, and I would like to see it broken, in a recognition of the traditional cultural truth that good criticism can be written by poets and novelists, and indeed by people whose professional concern is not with literature at all. Reviewing and criticism are separate activities, but the best literary journalism can provide genuine and valuable criticism, as Morris Dickstein has pointed out. What is needed are more journals that are prepared to publish long, serious, reflective essays or review-articles, as the London Review of Books does. Victoria Glendinning, writing as a biographer and literary journalist, has offered some judicious thoughts on the question, which summarize much of my argument:
No one could doubt that the application of the academic mind to literature has been salutary in bringing rigour and discipline into criticism: cleaner texts, scholarly annotations, precise analysis, intelligent â€” even transforming â€” interpretations and readings; and an intolerance for woolly emotional responses, vague inflated recommendations, and subjective wallowings of all kinds. But the academic mind, and the exigencies of the academic career, have had the effect of splitting off academic approaches to literature from the â€˜readingâ€™, in that word's widest sense, of ordinary peopleâ€¦ An ambitious lecturer in an English Department is writing for his peer group, not for the general public.
The tenor of this book has been pessimistic, but not, I hope, despairing. Some readers will find its arguments unconvincing, believing that what I see as problems are not problems at all. I can conceive of such a response coming from two quite different kinds of reader. The first would be moderate conservatives of placid and unreflective temperament who are happily engaged with their research and their teaching, and who believe that the discipline of English is in good heart, with lots of interesting books coming out and buoyant student demand. They support a genial pluralism in English studies, encouraging a hundred flowers to bloom, though putting up a cautious resistance to the extremes of foreign ideology and theory. The other kind would be academics who are committed to a tough professionalism on the American model, who believe that knowledge advances and becomes obsolete, that theory is essential, and that nothing of interest can be said about literature outside an institutional framework. In Lodge's characterology, they are Robyn Penroses aspiring to be Morris Zapps. What I have deplored or been sceptical about they would find admirable. They tend to be young, energetic, and ambitious, but there are by now professors of that outlook. All I can say to the objectors in both categories is that those who do not see a problem do not have a problem, and they can happily ignore what I have written. But other readers will, I imagine, accept the general drift of what I have said, whilst disagreeing on many points of detail.
Not wanting to seem too negative, I have outlined ways in which the discipline of English as currently constituted might divide, to the benefit of both parties. But knowing how the academic mind works, I am not optimistic about change. As Noel Annan wrote in his life of Leslie Stephen: â€˜The ingenuity in argument, the subtlety in drawing distinctions, the dexterous prevarications, the imperative reasons for procrastination, perpetually bewilder and confound the novice in university administration.â€™ In this respect, at least, little has altered since the nineteenth century. The most likely future is no overt change, with the discipline of English becoming less and less coherent, riven by feuds and revolts, but still presenting the external appearances of a large, well-established and respectable academic subject. It could go on for a long time in this condition, like the Spanish Empire in its centuries of decline.
"""
txt = txt.lower()
result = ''.join([i for i in txt if not i.isdigit()])
# define punctuation
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
resultp = ""
for char in result:
   if char not in punctuations:
       resultp = resultp + char
resultp = resultp.strip()

tokenized = sent_tokenize(resultp)
for i in tokenized:
    wordsList = nltk.word_tokenize(i) 
  
    # removing stop words from wordList 
    wordsList = [w for w in wordsList if not w in stop_words]  
  
    #  Using a Tagger. Which is part-of-speech  
    # tagger or POS-tagger.  
    tagged = nltk.pos_tag(wordsList) 
  
    print(tagged) 
 